// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRRbxjON0S41JlK8nc5aMhelEhbWcYeU',
    appId: '1:678521125119:web:0461f0badd9e61ac3f34ca',
    messagingSenderId: '678521125119',
    projectId: 'tracker-forinternship',
    authDomain: 'tracker-forinternship.firebaseapp.com',
    databaseURL: 'https://tracker-forinternship-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracker-forinternship.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB9EmwB7a3ZeVTdoNU3SJEY9qWmToaQmE',
    appId: '1:678521125119:android:0f2515440fed4e203f34ca',
    messagingSenderId: '678521125119',
    projectId: 'tracker-forinternship',
    databaseURL: 'https://tracker-forinternship-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracker-forinternship.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUkDQt_7qbfFcXFlJugO803De6I-fdbws',
    appId: '1:678521125119:ios:33fe02acedc856db3f34ca',
    messagingSenderId: '678521125119',
    projectId: 'tracker-forinternship',
    databaseURL: 'https://tracker-forinternship-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracker-forinternship.appspot.com',
    iosClientId: '678521125119-vpe9ihqpl1uq3gulmp0p1jid52836jqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUkDQt_7qbfFcXFlJugO803De6I-fdbws',
    appId: '1:678521125119:ios:33fe02acedc856db3f34ca',
    messagingSenderId: '678521125119',
    projectId: 'tracker-forinternship',
    databaseURL: 'https://tracker-forinternship-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracker-forinternship.appspot.com',
    iosClientId: '678521125119-vpe9ihqpl1uq3gulmp0p1jid52836jqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracker',
  );
}
